hacktoberfest-finder/hacktoberfest-finder

index.html
The essential meta tags are added in the `index.html` file.
Please note that the content of **keywords**, **og:image** meta tags are empty as those values can be set by the maintainer as needed.
**og:image** takes an image file that will show up when the site is shared on social platforms
**keywords** is for search engines
=> Added essential meta tags

.gitignore
Added the `app.js` and `app.css` files to the `.gitignore` file
=> Ignore the build files

readme.md
=> Extended the readme

index.html
#16 
Added break-words class from tailwind to h1 result.title container.
e.g.
=> Added break-words class to title container.

app.scss, index.html
Some work for #10.
Added some tailwind @screen directives to adjust grid columns. Used Calc() on column width to compensate for grid-gap.
Also added responsive font size class for the main title.
Let me know if its ok.
=> Responsive adjustments

dev.js, index.html
Fixes #19 
Conditionally renders `View More` button unless the API call gets rate limited.
Maintains a flag to show/hide view more button.
=> Add View More button to get more open issues

dev.js, index.html, tailwind.js
Modified `dev.js` to extract the repository name, and modified `index.html` to display it like this;
=> Closes #20 - Add repository name to card

dev.js
You need to specify the page to get new results. Otherwise you get the first page everytime
=> fix same results issue (#23)

license.md
In my opinion, every open-source project (which I assume this repo is one) should have a license. It could be an MIT License or an Apache license and many more.
=> Added License

index.html, package-lock.json
This will make it easier to click on a link.
=> Updated it so that the entire dive will have the link, not just the text

dev.js, index.html
- prevent double fetching process
- add loading text for better UI
=> Disable View More button once clicked

dev.js, package.json
Use fetch instead of axios to reduce the bundle size
=> Migrate to fetch

index.html
Think users should be honored directly :=)
=> Adding Username before repoTitle

index.html
Added specific media queries for heading, since Tailwinds predefined sizes aren't enough large
Fixes #37
=> Make heading larger

index.html
Added classes so that the new link is styled the same way as existing.
=> Dickyw issue#45

index.html
Please review and merge my PR for issue #45.
=> Changes for issue #45.

CONTRIBUTORS.md
Recording my github username in the list of contributors.
=> Added dickyw71 to list of contributors.

app.scss, index.html
=> box sizing changed

CONTRIBUTORS.md, app.scss, index.html
=> Accessibility

CONTRIBUTORS.md, dev.js, index.html, package-lock.json
=> add filter by language

CONTRIBUTORS.md, app.scss, dev.js, index.html
- Open link in new tab
- Show language when is selected
- Hide language list when one language is selected
- Tidy up some style
=> Hide language list when is selected

CONTRIBUTORS.md, assets/js/app.js, index.html, tailwind.config.js
`index.html`
- Added `@click` to filter toggle button
- Fixed `@click` callback for language buttons
- Added `{{language}}` to display correct language as button text
`app.js`
- Fixed template string in fetch (missing backticks ``)
If applicable, please leave some screenshots showing the changes you've made.
> Closes #126
=> fixed: language filter

index.html, tailwind.config.js
Added few classes to make site more responsive
> Closes #127
=> added: responsive

assets/js/app.js
plus added condition when all issues are loaded to hide load more button
Fixed page property not incrementing after successful fetch
Added condition when all issues are loaded to hide load more button
If applicable, please leave some screenshots showing the changes you've made.
> Closes #139
=> fixed: issue with page not incrementing

assets/js/app.js, index.html
There are two issues with the repo names that this PR fixes.
1. When you load more results it doesn't show the repo name or last updated date
2. The page currently shows the name of the user that raised the issue as the repo author instead of the actual owner
If applicable, please leave some screenshots showing the changes you've made.
Missing repo name and updated date:
Fixed page show correct author and issue raiser below:
=> Fix repo names

CONTRIBUTORS.md, assets/css/app.css, assets/js/app.js, index.html
I've added in many more languages (491 of them) and implemented a way to search them, keeping the current list as a "top language" list that are shown by default.
The list was taken from [oprogramador/github-languages](https://github.com/oprogramador/github-languages), further info [here](https://brainhub.eu/blog/most-popular-languages-on-github/).
I've also changed the language filter pop up to close when you click off of it.
If applicable, please leave some screenshots showing the changes you've made.
Default "Top Languages"
Searching for other languages
N/A
=> Add more languages

CONTRIBUTORS.md, assets/js/app.js, index.html
Labels didn't show emojis. They were changed by Github to for example : wrench :
I called the emojis endpoint Github provides ( https://developer.github.com/v3/emojis/ )
Solves no issues, is an enhancement
=> Added emoji support in labels

CONTRIBUTORS.md, index.html
Change the position of label.
Closes #148
=> Changes label position for hacktoberfestfinder-UI

package.json
Deps updated to the latest versions
=> deps updated

CONTRIBUTORS.md, index.html, src/js/app.js
This PR fixes the language and sorting filters (#179)
=> Fix language and sorting filters

src/js/app.js
Add `created:2020` to API request to only show issues created this year
=> Only show issues which were created this year

index.html
Added a skeleton loader when fetching data. Resolves #188 
The grey boxes are animated with the Tailwind `animate-pulse` class
=> Add skeleton loader

CONTRIBUTORS.md, index.html
=> Add Padding for Mobile Responsivity

CONTRIBUTORS.md, hot, index.html, src/js/app.js
As we discussed on #195 here is my PR.
=> Back to top button & functionality

CONTRIBUTORS.md, src/js/app.js, src/js/languages.js
A quick description of the changes made in this pull request. Make sure to reference the related issue (if there is one).
=> solving #209 (Languages not alphabetically sorted)

README.md, index.html, src/js/app.js, src/js/languages.js
Updated the list of languages, to get the most relevants on top. The list was taken from an older version from this repository
=> Top languages

CONTRIBUTING.md
=> Test our little action..

CONTRIBUTORS.md, index.html
Removed hardcoded year from og tags
Fixes https://github.com/hacktoberfest-finder/hacktoberfest-finder/issues/223
=> fix: remove hardcoded year from og tags
